"""
FTD-RTAG: Canonical Report Registry.

Single source of truth for all PHOENIX LIO report descriptors.
Each report declares its family, tier, dependencies, overlapping reports,
constitutional scope, archive priority, and evidence requirements.

Pure data — no I/O, no side effects. Import-safe.

Hard rule: The registry MUST NOT be mutated at runtime.
           All reporting governance remains under human constitutional authority.
"""
from __future__ import annotations
from typing import Any, Dict

REGISTRY_VERSION = "2.0"

# ── Export tiers ──────────────────────────────────────────────────────────────
TIER_CORE        = "CORE"
TIER_RESEARCH    = "RESEARCH"
TIER_GOVERNANCE  = "GOVERNANCE"
TIER_EPISTEMIC   = "EPISTEMIC"
TIER_CONTINUITY  = "CONTINUITY"
TIER_FORENSICS   = "FORENSICS"

# ── Archive priorities ────────────────────────────────────────────────────────
PRIORITY_CRITICAL = "CRITICAL"
PRIORITY_HIGH     = "HIGH"
PRIORITY_MEDIUM   = "MEDIUM"
PRIORITY_LOW      = "LOW"

# ── Report families ───────────────────────────────────────────────────────────
FAMILY_ECONOMIC        = "ECONOMIC"
FAMILY_COGNITIVE       = "COGNITIVE"
FAMILY_GOVERNANCE      = "GOVERNANCE"
FAMILY_EPISTEMIC       = "EPISTEMIC"
FAMILY_CONTINUITY      = "CONTINUITY"
FAMILY_HUMAN_ALIGNMENT = "HUMAN_ALIGNMENT"
FAMILY_REPLAY          = "REPLAY"
FAMILY_FORENSICS       = "FORENSICS"

# ── Known sets ────────────────────────────────────────────────────────────────
KNOWN_FAMILIES: frozenset = frozenset({
    FAMILY_ECONOMIC, FAMILY_COGNITIVE, FAMILY_GOVERNANCE,
    FAMILY_EPISTEMIC, FAMILY_CONTINUITY, FAMILY_HUMAN_ALIGNMENT,
    FAMILY_REPLAY, FAMILY_FORENSICS,
})

KNOWN_TIERS: frozenset = frozenset({
    TIER_CORE, TIER_RESEARCH, TIER_GOVERNANCE,
    TIER_EPISTEMIC, TIER_CONTINUITY, TIER_FORENSICS,
})

KNOWN_PRIORITIES: frozenset = frozenset({
    PRIORITY_CRITICAL, PRIORITY_HIGH, PRIORITY_MEDIUM, PRIORITY_LOW,
})

# Required fields for every registry entry.
REGISTRY_REQUIRED_FIELDS: tuple = (
    "report_id", "name", "report_family", "doctrine_version",
    "export_tier", "endpoint", "bundle_key", "dependencies",
    "overlapping_reports", "constitutional_scope", "archive_priority",
    "evidence_requirements", "description",
)

# ── Canonical report registry ─────────────────────────────────────────────────

REPORT_REGISTRY: Dict[str, Dict[str, Any]] = {

    "SUMMARY": {
        "report_id":           "SUMMARY",
        "name":                "Trading Summary",
        "report_family":       FAMILY_ECONOMIC,
        "doctrine_version":    "1.0",
        "export_tier":         TIER_CORE,
        "endpoint":            "/api/learning-intelligence/summary",
        "bundle_key":          "summary",
        "dependencies":        [],
        "overlapping_reports": ["ECOLOGY", "RL_LEARNING"],
        "constitutional_scope": "ECONOMIC_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 0},
        "description": "Core economic performance summary — PnL, win rate, session stats",
    },

    "PATTERNS": {
        "report_id":           "PATTERNS",
        "name":                "Pattern Library",
        "report_family":       FAMILY_COGNITIVE,
        "doctrine_version":    "1.0",
        "export_tier":         TIER_RESEARCH,
        "endpoint":            "/api/learning-intelligence/patterns",
        "bundle_key":          "patterns",
        "dependencies":        ["SUMMARY"],
        "overlapping_reports": ["COGNITION"],
        "constitutional_scope": "COGNITIVE_OBSERVABILITY",
        "archive_priority":    PRIORITY_MEDIUM,
        "evidence_requirements": {"min_trades": 10},
        "description": "Learned strategy patterns and regime-specific pattern library",
    },

    "NEGATIVE_MEMORY": {
        "report_id":           "NEGATIVE_MEMORY",
        "name":                "Negative Memory Archive",
        "report_family":       FAMILY_COGNITIVE,
        "doctrine_version":    "1.0",
        "export_tier":         TIER_RESEARCH,
        "endpoint":            "/api/learning-intelligence/negative-memory",
        "bundle_key":          "negative_memory",
        "dependencies":        ["SUMMARY"],
        "overlapping_reports": ["MEMORY_PRESSURE"],
        "constitutional_scope": "COGNITIVE_OBSERVABILITY",
        "archive_priority":    PRIORITY_MEDIUM,
        "evidence_requirements": {"min_trades": 5},
        "description": "Aversion catalog — high-loss patterns and adverse regime memory",
    },

    "ECOLOGY": {
        "report_id":           "ECOLOGY",
        "name":                "Strategy Ecology",
        "report_family":       FAMILY_ECONOMIC,
        "doctrine_version":    "1.0",
        "export_tier":         TIER_CORE,
        "endpoint":            "/api/learning-intelligence/ecology",
        "bundle_key":          "ecology",
        "dependencies":        ["SUMMARY"],
        "overlapping_reports": ["SUMMARY", "REGIME_CARTOGRAPHY"],
        "constitutional_scope": "ECONOMIC_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 10},
        "description": "Strategy ecosystem health — regime distribution, strategy population balance",
    },

    "RL_LEARNING": {
        "report_id":           "RL_LEARNING",
        "name":                "RL Learning Intelligence",
        "report_family":       FAMILY_ECONOMIC,
        "doctrine_version":    "1.0",
        "export_tier":         TIER_CORE,
        "endpoint":            "/api/learning-intelligence/rl",
        "bundle_key":          "rl",
        "dependencies":        ["SUMMARY"],
        "overlapping_reports": ["COGNITION", "SUMMARY"],
        "constitutional_scope": "ECONOMIC_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 10},
        "description": "RL policy learning state — Q-values, reward shaping, policy evolution",
    },

    "TOPOLOGY": {
        "report_id":           "TOPOLOGY",
        "name":                "Strategy Topology",
        "report_family":       FAMILY_COGNITIVE,
        "doctrine_version":    "1.0",
        "export_tier":         TIER_RESEARCH,
        "endpoint":            "/api/learning-intelligence/topology",
        "bundle_key":          "topology",
        "dependencies":        ["PATTERNS", "ECOLOGY"],
        "overlapping_reports": ["PATTERNS"],
        "constitutional_scope": "COGNITIVE_OBSERVABILITY",
        "archive_priority":    PRIORITY_MEDIUM,
        "evidence_requirements": {"min_trades": 20},
        "description": "Strategy relationship topology — decision surface mapping",
    },

    "COGNITION": {
        "report_id":           "COGNITION",
        "name":                "Cognitive State",
        "report_family":       FAMILY_COGNITIVE,
        "doctrine_version":    "1.0",
        "export_tier":         TIER_RESEARCH,
        "endpoint":            "/api/learning-intelligence/cognition",
        "bundle_key":          "cognition",
        "dependencies":        ["RL_LEARNING", "PATTERNS"],
        "overlapping_reports": ["RL_LEARNING", "MEMORY_PRESSURE"],
        "constitutional_scope": "COGNITIVE_OBSERVABILITY",
        "archive_priority":    PRIORITY_MEDIUM,
        "evidence_requirements": {"min_trades": 10},
        "description": "Cognitive architecture state — ontology drift, belief updating, adaptation velocity",
    },

    "SOVEREIGN_READINESS": {
        "report_id":           "SOVEREIGN_READINESS",
        "name":                "Sovereign Readiness",
        "report_family":       FAMILY_GOVERNANCE,
        "doctrine_version":    "1.0",
        "export_tier":         TIER_GOVERNANCE,
        "endpoint":            "/api/learning-intelligence/sovereign-readiness",
        "bundle_key":          "sovereign_readiness",
        "dependencies":        ["SUMMARY", "COGNITION"],
        "overlapping_reports": ["GAGS"],
        "constitutional_scope": "GOVERNANCE_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 30},
        "description": "Governance readiness diagnostics — sovereignty gate assessment",
    },

    "ALPHA_DISCOVERY": {
        "report_id":           "ALPHA_DISCOVERY",
        "name":                "Alpha Discovery",
        "report_family":       FAMILY_ECONOMIC,
        "doctrine_version":    "1.0",
        "export_tier":         TIER_RESEARCH,
        "endpoint":            "/api/learning-intelligence/alpha-discovery",
        "bundle_key":          "alpha_discovery",
        "dependencies":        ["SUMMARY", "ECOLOGY"],
        "overlapping_reports": ["ECONOMIC_GROUND_TRUTH"],
        "constitutional_scope": "ECONOMIC_OBSERVABILITY",
        "archive_priority":    PRIORITY_MEDIUM,
        "evidence_requirements": {"min_trades": 20},
        "description": "Alpha signal discovery — edge identification and regime-specific alpha",
    },

    "SESSION_ATTRIBUTION": {
        "report_id":           "SESSION_ATTRIBUTION",
        "name":                "Session Attribution",
        "report_family":       FAMILY_FORENSICS,
        "doctrine_version":    "1.0",
        "export_tier":         TIER_FORENSICS,
        "endpoint":            "/api/learning-intelligence/session-attribution",
        "bundle_key":          "session_attribution",
        "dependencies":        ["SUMMARY"],
        "overlapping_reports": ["REGIME_CARTOGRAPHY"],
        "constitutional_scope": "FORENSICS_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 10},
        "description": "Session-level forensics — NY/LN/AS/EU attribution and performance breakdown",
    },

    "EXPLORATION_DIAGNOSTICS": {
        "report_id":           "EXPLORATION_DIAGNOSTICS",
        "name":                "Exploration Diagnostics",
        "report_family":       FAMILY_REPLAY,
        "doctrine_version":    "1.0",
        "export_tier":         TIER_RESEARCH,
        "endpoint":            "/api/learning-intelligence/exploration-diagnostics",
        "bundle_key":          "exploration_diagnostics",
        "dependencies":        ["SUMMARY"],
        "overlapping_reports": ["EXPLORATION_ECONOMIC_ATTRIBUTION", "EIOD"],
        "constitutional_scope": "REPLAY_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 10},
        "description": "Exploration health — epsilon decay, trial diversity, exploration effectiveness",
    },

    "EXPLORATION_ECONOMIC_ATTRIBUTION": {
        "report_id":           "EXPLORATION_ECONOMIC_ATTRIBUTION",
        "name":                "Exploration Economic Attribution",
        "report_family":       FAMILY_REPLAY,
        "doctrine_version":    "1.0",
        "export_tier":         TIER_RESEARCH,
        "endpoint":            "/api/learning-intelligence/exploration-economic-attribution",
        "bundle_key":          "exploration_economic_attribution",
        "dependencies":        ["EXPLORATION_DIAGNOSTICS", "ECONOMIC_GROUND_TRUTH"],
        "overlapping_reports": ["EXPLORATION_DIAGNOSTICS"],
        "constitutional_scope": "REPLAY_OBSERVABILITY",
        "archive_priority":    PRIORITY_MEDIUM,
        "evidence_requirements": {"min_trades": 20},
        "description": "Economic cost/benefit of exploration — PnL attribution to exploration vs exploitation",
    },

    "ECONOMIC_GROUND_TRUTH": {
        "report_id":           "ECONOMIC_GROUND_TRUTH",
        "name":                "Economic Ground Truth",
        "report_family":       FAMILY_ECONOMIC,
        "doctrine_version":    "1.0",
        "export_tier":         TIER_CORE,
        "endpoint":            "/api/learning-intelligence/economic-ground-truth",
        "bundle_key":          "economic_ground_truth",
        "dependencies":        [],
        "overlapping_reports": ["SUMMARY", "TIMEFRAME_SURVIVABILITY"],
        "constitutional_scope": "ECONOMIC_OBSERVABILITY",
        "archive_priority":    PRIORITY_CRITICAL,
        "evidence_requirements": {"min_trades": 0},
        "description": "Ground truth economic performance — fees, slippage, net/gross PnL, Sharpe-family",
    },

    "TIMEFRAME_SURVIVABILITY": {
        "report_id":           "TIMEFRAME_SURVIVABILITY",
        "name":                "Timeframe Survivability",
        "report_family":       FAMILY_ECONOMIC,
        "doctrine_version":    "1.0",
        "export_tier":         TIER_RESEARCH,
        "endpoint":            "/api/learning-intelligence/timeframe-survivability",
        "bundle_key":          "timeframe_survivability",
        "dependencies":        ["ECONOMIC_GROUND_TRUTH"],
        "overlapping_reports": ["REGIME_CARTOGRAPHY", "ECONOMIC_GROUND_TRUTH"],
        "constitutional_scope": "ECONOMIC_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 30},
        "description": "Survivability across holding periods — how strategy performance degrades over time",
    },

    "REGIME_CARTOGRAPHY": {
        "report_id":           "REGIME_CARTOGRAPHY",
        "name":                "Regime Survivability Cartography",
        "report_family":       FAMILY_ECONOMIC,
        "doctrine_version":    "1.0",
        "export_tier":         TIER_RESEARCH,
        "endpoint":            "/api/learning-intelligence/regime-survivability-cartography",
        "bundle_key":          "regime_survivability_cartography",
        "dependencies":        ["TIMEFRAME_SURVIVABILITY", "SESSION_ATTRIBUTION"],
        "overlapping_reports": ["TIMEFRAME_SURVIVABILITY", "ECOLOGY"],
        "constitutional_scope": "ECONOMIC_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 50},
        "description": "Regime-indexed survivability map — performance across market regimes",
    },

    "MEMORY_PRESSURE": {
        "report_id":           "MEMORY_PRESSURE",
        "name":                "Memory Pressure Dynamics",
        "report_family":       FAMILY_COGNITIVE,
        "doctrine_version":    "1.0",
        "export_tier":         TIER_RESEARCH,
        "endpoint":            "/api/learning-intelligence/memory-pressure-dynamics",
        "bundle_key":          "memory_pressure_dynamics",
        "dependencies":        ["COGNITION", "NEGATIVE_MEMORY"],
        "overlapping_reports": ["COGNITION", "NEGATIVE_MEMORY"],
        "constitutional_scope": "COGNITIVE_OBSERVABILITY",
        "archive_priority":    PRIORITY_MEDIUM,
        "evidence_requirements": {"min_trades": 20},
        "description": "Memory buffer pressure — eviction dynamics, aversion memory saturation",
    },

    "COUNTERFACTUAL_LAB": {
        "report_id":           "COUNTERFACTUAL_LAB",
        "name":                "Counterfactual Interventions",
        "report_family":       FAMILY_REPLAY,
        "doctrine_version":    "1.0",
        "export_tier":         TIER_RESEARCH,
        "endpoint":            "/api/learning-intelligence/counterfactual-interventions",
        "bundle_key":          "counterfactual_interventions",
        "dependencies":        ["REGIME_CARTOGRAPHY", "EXPLORATION_DIAGNOSTICS"],
        "overlapping_reports": ["REGIME_CARTOGRAPHY"],
        "constitutional_scope": "REPLAY_OBSERVABILITY",
        "archive_priority":    PRIORITY_MEDIUM,
        "evidence_requirements": {"min_trades": 50},
        "description": "Counterfactual analysis — what-if interventions on strategy parameters",
    },

    "GAGS": {
        "report_id":           "GAGS",
        "name":                "Adaptive Governance Simulator",
        "report_family":       FAMILY_GOVERNANCE,
        "doctrine_version":    "1.0",
        "export_tier":         TIER_GOVERNANCE,
        "endpoint":            "/api/learning-intelligence/adaptive-governance-simulator",
        "bundle_key":          "adaptive_governance_simulator",
        "dependencies":        ["SOVEREIGN_READINESS", "ECONOMIC_GROUND_TRUTH"],
        "overlapping_reports": ["GADD", "SOVEREIGN_READINESS"],
        "constitutional_scope": "GOVERNANCE_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 30},
        "description": "Governance parameter simulation — threshold sensitivity and adaptive governance scenarios",
    },

    "GADD": {
        "report_id":           "GADD",
        "name":                "Governed Adaptive Doctrine",
        "report_family":       FAMILY_GOVERNANCE,
        "doctrine_version":    "1.0",
        "export_tier":         TIER_GOVERNANCE,
        "endpoint":            "/api/learning-intelligence/governed-adaptive-doctrine",
        "bundle_key":          "governed_adaptive_doctrine",
        "dependencies":        ["GAGS"],
        "overlapping_reports": ["GAGS"],
        "constitutional_scope": "GOVERNANCE_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 30},
        "description": "Active governance doctrine — current adaptive doctrine state and constitutional compliance",
    },

    "GRVL": {
        "report_id":           "GRVL",
        "name":                "Reality Verification",
        "report_family":       FAMILY_GOVERNANCE,
        "doctrine_version":    "1.0",
        "export_tier":         TIER_GOVERNANCE,
        "endpoint":            "/api/learning-intelligence/reality-verification",
        "bundle_key":          "reality_verification",
        "dependencies":        ["ECONOMIC_GROUND_TRUTH"],
        "overlapping_reports": ["GADD"],
        "constitutional_scope": "GOVERNANCE_OBSERVABILITY",
        "archive_priority":    PRIORITY_CRITICAL,
        "evidence_requirements": {"min_trades": 0},
        "description": "Reality gate verification — alignment of engine assumptions with market ground truth",
    },

    "GMPD": {
        "report_id":           "GMPD",
        "name":                "Guarded Micro Pilot",
        "report_family":       FAMILY_GOVERNANCE,
        "doctrine_version":    "1.0",
        "export_tier":         TIER_GOVERNANCE,
        "endpoint":            "/api/learning-intelligence/guarded-micro-pilot",
        "bundle_key":          "guarded_micro_pilot",
        "dependencies":        ["GRVL", "SOVEREIGN_READINESS"],
        "overlapping_reports": ["GRVL"],
        "constitutional_scope": "GOVERNANCE_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 50},
        "description": "Micro-pilot deployment governance — staged live readiness gating",
    },

    "LHEO": {
        "report_id":           "LHEO",
        "name":                "Long-Horizon Evolution",
        "report_family":       FAMILY_CONTINUITY,
        "doctrine_version":    "1.0",
        "export_tier":         TIER_CONTINUITY,
        "endpoint":            "/api/learning-intelligence/long-horizon-evolution",
        "bundle_key":          "long_horizon_evolution",
        "dependencies":        ["COGNITION", "EXPLORATION_DIAGNOSTICS"],
        "overlapping_reports": ["COGNITION", "EIOD"],
        "constitutional_scope": "CONTINUITY_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 50},
        "description": "Long-horizon cognitive evolution — ontology drift, belief continuity, adaptation lineage",
    },

    "CKPD": {
        "report_id":           "CKPD",
        "name":                "Constitutional Recovery Observatory",
        "report_family":       FAMILY_CONTINUITY,
        "doctrine_version":    "1.21",
        "export_tier":         TIER_CONTINUITY,
        "endpoint":            "/api/learning-intelligence/constitutional-recovery-observatory",
        "bundle_key":          "constitutional_recovery_observatory",
        "dependencies":        [],
        "overlapping_reports": ["LHEO"],
        "constitutional_scope": "CONTINUITY_OBSERVABILITY",
        "archive_priority":    PRIORITY_CRITICAL,
        "evidence_requirements": {"min_trades": 10},
        "description": "FTD-CKPD: Knowledge preservation & catastrophic recovery readiness — 7 recovery metrics",
    },

    "EIOD": {
        "report_id":           "EIOD",
        "name":                "Epistemic Integrity Observatory",
        "report_family":       FAMILY_EPISTEMIC,
        "doctrine_version":    "1.22",
        "export_tier":         TIER_EPISTEMIC,
        "endpoint":            "/api/learning-intelligence/epistemic-integrity-observatory",
        "bundle_key":          "epistemic_integrity_observatory",
        "dependencies":        ["EXPLORATION_DIAGNOSTICS"],
        "overlapping_reports": ["LHEO"],
        "constitutional_scope": "EPISTEMIC_OBSERVABILITY",
        "archive_priority":    PRIORITY_CRITICAL,
        "evidence_requirements": {"min_trades": 10},
        "description": "FTD-EIOD: Scientific method governance — 8 epistemic metrics, 6 classifications",
    },

    "HMAO": {
        "report_id":           "HMAO",
        "name":                "Human Meaning Alignment Observatory",
        "report_family":       FAMILY_HUMAN_ALIGNMENT,
        "doctrine_version":    "1.23",
        "export_tier":         TIER_CONTINUITY,
        "endpoint":            "/api/learning-intelligence/human-meaning-alignment",
        "bundle_key":          "human_meaning_alignment",
        "dependencies":        ["EXPLORATION_DIAGNOSTICS", "EIOD"],
        "overlapping_reports": ["EIOD"],
        "constitutional_scope": "ALIGNMENT_OBSERVABILITY",
        "archive_priority":    PRIORITY_CRITICAL,
        "evidence_requirements": {"min_trades": 10},
        "description": "FTD-HMAO: Human purpose alignment governance — 8 alignment metrics, 6 classifications",
    },

    # ── Phase-F: Adaptive Equilibrium & Capital Discipline ───────────────────

    "KELLY_EFFICIENCY": {
        "report_id":           "KELLY_EFFICIENCY",
        "name":                "Kelly Capital Efficiency",
        "report_family":       FAMILY_ECONOMIC,
        "doctrine_version":    "1.35",
        "export_tier":         TIER_RESEARCH,
        "endpoint":            "/api/equilibrium/kelly",
        "bundle_key":          "kelly_efficiency",
        "dependencies":        ["ECONOMIC_GROUND_TRUTH"],
        "overlapping_reports": ["ADAPTIVE_EQUILIBRIUM"],
        "constitutional_scope": "ECONOMIC_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 5},
        "description": "Kelly capital efficiency — optimal vs actual position sizing with OPTIMAL/ADEQUATE/SUBOPTIMAL/NEGLIGENT states",
    },

    "DRAWDOWN_DYNAMICS": {
        "report_id":           "DRAWDOWN_DYNAMICS",
        "name":                "Drawdown Dynamics Engine",
        "report_family":       FAMILY_ECONOMIC,
        "doctrine_version":    "1.35",
        "export_tier":         TIER_RESEARCH,
        "endpoint":            "/api/equilibrium/drawdown",
        "bundle_key":          "drawdown_dynamics",
        "dependencies":        ["ECONOMIC_GROUND_TRUTH"],
        "overlapping_reports": ["ADAPTIVE_EQUILIBRIUM"],
        "constitutional_scope": "ECONOMIC_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 5},
        "description": "Drawdown dynamics — multi-phase peak/trough/recovery analysis with STABLE/RECOVERING/DETERIORATING/CRITICAL states",
    },

    "RETURN_CONSISTENCY": {
        "report_id":           "RETURN_CONSISTENCY",
        "name":                "Return Consistency Engine",
        "report_family":       FAMILY_ECONOMIC,
        "doctrine_version":    "1.35",
        "export_tier":         TIER_RESEARCH,
        "endpoint":            "/api/equilibrium/consistency",
        "bundle_key":          "return_consistency",
        "dependencies":        ["ECONOMIC_GROUND_TRUTH"],
        "overlapping_reports": ["ADAPTIVE_EQUILIBRIUM", "EXPECTANCY_STABILITY"],
        "constitutional_scope": "ECONOMIC_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 10},
        "description": "Return consistency — rolling window variance and positive-ratio scoring with CONSISTENT/ADEQUATE/VARIABLE/ERRATIC states",
    },

    "CAPITAL_UTILIZATION": {
        "report_id":           "CAPITAL_UTILIZATION",
        "name":                "Capital Utilization Engine",
        "report_family":       FAMILY_ECONOMIC,
        "doctrine_version":    "1.35",
        "export_tier":         TIER_RESEARCH,
        "endpoint":            "/api/equilibrium/utilization",
        "bundle_key":          "capital_utilization",
        "dependencies":        ["ECONOMIC_GROUND_TRUTH"],
        "overlapping_reports": ["ADAPTIVE_EQUILIBRIUM"],
        "constitutional_scope": "ECONOMIC_OBSERVABILITY",
        "archive_priority":    PRIORITY_MEDIUM,
        "evidence_requirements": {"min_trades": 5},
        "description": "Capital utilization — PnL-per-unit efficiency and sizing coefficient of variation with EFFICIENT/ADEQUATE/UNDERUTILIZED/OVEREXTENDED states",
    },

    "EQUILIBRIUM_BAND": {
        "report_id":           "EQUILIBRIUM_BAND",
        "name":                "Equilibrium Band Engine",
        "report_family":       FAMILY_ECONOMIC,
        "doctrine_version":    "1.35",
        "export_tier":         TIER_RESEARCH,
        "endpoint":            "/api/equilibrium/band",
        "bundle_key":          "equilibrium_band",
        "dependencies":        ["ECONOMIC_GROUND_TRUTH"],
        "overlapping_reports": ["ADAPTIVE_EQUILIBRIUM"],
        "constitutional_scope": "ECONOMIC_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 20},
        "description": "Equilibrium band — 2.5-sigma statistical band detection with IN_BAND/APPROACHING/OUTSIDE_BAND/FAR_OUTSIDE states",
    },

    "DISCIPLINE_COST": {
        "report_id":           "DISCIPLINE_COST",
        "name":                "Discipline Cost Engine",
        "report_family":       FAMILY_ECONOMIC,
        "doctrine_version":    "1.35",
        "export_tier":         TIER_RESEARCH,
        "endpoint":            "/api/equilibrium/discipline-cost",
        "bundle_key":          "discipline_cost",
        "dependencies":        ["ECONOMIC_GROUND_TRUTH"],
        "overlapping_reports": ["ADAPTIVE_EQUILIBRIUM", "DISCIPLINE_MEMORY"],
        "constitutional_scope": "ECONOMIC_OBSERVABILITY",
        "archive_priority":    PRIORITY_MEDIUM,
        "evidence_requirements": {"min_trades": 5},
        "description": "Discipline cost — quantifies economic cost of over-caution and under-discipline with COST_MINIMAL/MODERATE/SIGNIFICANT/SEVERE states",
    },

    "ADAPTIVE_EQUILIBRIUM": {
        "report_id":           "ADAPTIVE_EQUILIBRIUM",
        "name":                "Adaptive Equilibrium Orchestration",
        "report_family":       FAMILY_ECONOMIC,
        "doctrine_version":    "1.35",
        "export_tier":         TIER_CORE,
        "endpoint":            "/api/equilibrium/orchestration",
        "bundle_key":          "adaptive_equilibrium",
        "dependencies":        [
            "KELLY_EFFICIENCY", "DRAWDOWN_DYNAMICS", "RETURN_CONSISTENCY",
            "CAPITAL_UTILIZATION", "EQUILIBRIUM_BAND", "DISCIPLINE_COST",
        ],
        "overlapping_reports": ["ECONOMIC_TRUTH", "SURVIVABILITY_EVOLUTION"],
        "constitutional_scope": "ECONOMIC_OBSERVABILITY",
        "archive_priority":    PRIORITY_CRITICAL,
        "evidence_requirements": {"min_trades": 5},
        "description": "Adaptive equilibrium orchestration — Phase-F EQ lineage, BALANCED/ADAPTING/STRESSED/CRITICAL tiers (capital mathematics layer)",
    },

    # ── Phase-B: Cross-PRP Wiring Audit ──────────────────────────────────────

    "WIRING_CONSTITUTION": {
        "report_id":           "WIRING_CONSTITUTION",
        "name":                "Wiring Constitution Audit",
        "report_family":       FAMILY_GOVERNANCE,
        "doctrine_version":    "1.25",
        "export_tier":         TIER_GOVERNANCE,
        "endpoint":            "/api/wiring-audit/constitution",
        "bundle_key":          "wiring_constitution",
        "dependencies":        [],
        "overlapping_reports": ["WIRING_FULL_REPORT"],
        "constitutional_scope": "WIRING_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 0},
        "description": "Constitutional wiring audit — verifies all constitutional invariants are propagated correctly",
    },

    "WIRING_PROPAGATION": {
        "report_id":           "WIRING_PROPAGATION",
        "name":                "Wiring Propagation Audit",
        "report_family":       FAMILY_GOVERNANCE,
        "doctrine_version":    "1.25",
        "export_tier":         TIER_GOVERNANCE,
        "endpoint":            "/api/wiring-audit/propagation",
        "bundle_key":          "wiring_propagation",
        "dependencies":        [],
        "overlapping_reports": ["WIRING_FULL_REPORT"],
        "constitutional_scope": "WIRING_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 0},
        "description": "Signal propagation wiring audit — verifies data flows correctly across all PRP phases",
    },

    "WIRING_DEPENDENCIES": {
        "report_id":           "WIRING_DEPENDENCIES",
        "name":                "Wiring Dependencies Audit",
        "report_family":       FAMILY_GOVERNANCE,
        "doctrine_version":    "1.25",
        "export_tier":         TIER_GOVERNANCE,
        "endpoint":            "/api/wiring-audit/dependencies",
        "bundle_key":          "wiring_dependencies",
        "dependencies":        [],
        "overlapping_reports": ["WIRING_FULL_REPORT"],
        "constitutional_scope": "WIRING_OBSERVABILITY",
        "archive_priority":    PRIORITY_MEDIUM,
        "evidence_requirements": {"min_trades": 0},
        "description": "Cross-module dependency wiring audit — verifies import chains are clean and fail-open",
    },

    "WIRING_ARCHIVE": {
        "report_id":           "WIRING_ARCHIVE",
        "name":                "Wiring Archive Audit",
        "report_family":       FAMILY_GOVERNANCE,
        "doctrine_version":    "1.25",
        "export_tier":         TIER_GOVERNANCE,
        "endpoint":            "/api/wiring-audit/archive",
        "bundle_key":          "wiring_archive",
        "dependencies":        [],
        "overlapping_reports": ["WIRING_FULL_REPORT"],
        "constitutional_scope": "WIRING_OBSERVABILITY",
        "archive_priority":    PRIORITY_MEDIUM,
        "evidence_requirements": {"min_trades": 0},
        "description": "Archive wiring audit — verifies QPR bundle keys and report registry alignment",
    },

    "WIRING_RENDERING": {
        "report_id":           "WIRING_RENDERING",
        "name":                "Wiring Rendering Audit",
        "report_family":       FAMILY_GOVERNANCE,
        "doctrine_version":    "1.25",
        "export_tier":         TIER_GOVERNANCE,
        "endpoint":            "/api/wiring-audit/rendering",
        "bundle_key":          "wiring_rendering",
        "dependencies":        [],
        "overlapping_reports": ["WIRING_FULL_REPORT"],
        "constitutional_scope": "WIRING_OBSERVABILITY",
        "archive_priority":    PRIORITY_MEDIUM,
        "evidence_requirements": {"min_trades": 0},
        "description": "Rendering wiring audit — verifies dashboard endpoints and UI tile wiring correctness",
    },

    "WIRING_COMPRESSION": {
        "report_id":           "WIRING_COMPRESSION",
        "name":                "Wiring Compression Audit",
        "report_family":       FAMILY_GOVERNANCE,
        "doctrine_version":    "1.25",
        "export_tier":         TIER_GOVERNANCE,
        "endpoint":            "/api/wiring-audit/compression",
        "bundle_key":          "wiring_compression",
        "dependencies":        [],
        "overlapping_reports": ["WIRING_FULL_REPORT", "COMPRESSION_ORCHESTRATION"],
        "constitutional_scope": "WIRING_OBSERVABILITY",
        "archive_priority":    PRIORITY_MEDIUM,
        "evidence_requirements": {"min_trades": 0},
        "description": "Compression wiring audit — verifies compression subsystem integration with main PRP chain",
    },

    "WIRING_FULL_REPORT": {
        "report_id":           "WIRING_FULL_REPORT",
        "name":                "Cross-PRP Full Wiring Report",
        "report_family":       FAMILY_GOVERNANCE,
        "doctrine_version":    "1.25",
        "export_tier":         TIER_GOVERNANCE,
        "endpoint":            "/api/wiring-audit/full-report",
        "bundle_key":          "wiring_full_report",
        "dependencies":        [
            "WIRING_CONSTITUTION", "WIRING_PROPAGATION", "WIRING_DEPENDENCIES",
            "WIRING_ARCHIVE", "WIRING_RENDERING", "WIRING_COMPRESSION",
        ],
        "overlapping_reports": ["WIRING_CONSTITUTION", "WIRING_PROPAGATION"],
        "constitutional_scope": "WIRING_OBSERVABILITY",
        "archive_priority":    PRIORITY_CRITICAL,
        "evidence_requirements": {"min_trades": 0},
        "description": "Full cross-PRP wiring audit synthesis — comprehensive integration health across all phases",
    },

    "WIRING_HEALTH": {
        "report_id":           "WIRING_HEALTH",
        "name":                "Wiring Audit Health",
        "report_family":       FAMILY_GOVERNANCE,
        "doctrine_version":    "1.25",
        "export_tier":         TIER_GOVERNANCE,
        "endpoint":            "/api/wiring-audit/health",
        "bundle_key":          "wiring_health",
        "dependencies":        ["WIRING_FULL_REPORT"],
        "overlapping_reports": ["WIRING_FULL_REPORT"],
        "constitutional_scope": "WIRING_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 0},
        "description": "Wiring audit subsystem health — single-line operational status for boot visibility",
    },

    # ── Phase-C: Compression Intelligence ────────────────────────────────────

    "COMPRESSION_EXECUTIVE": {
        "report_id":           "COMPRESSION_EXECUTIVE",
        "name":                "Compression Executive Summary",
        "report_family":       FAMILY_GOVERNANCE,
        "doctrine_version":    "1.26",
        "export_tier":         TIER_GOVERNANCE,
        "endpoint":            "/api/compression/executive",
        "bundle_key":          "compression_executive",
        "dependencies":        [],
        "overlapping_reports": ["COMPRESSION_ORCHESTRATION"],
        "constitutional_scope": "COMPRESSION_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 0},
        "description": "Compression executive summary — high-level context compression health and key metrics",
    },

    "COMPRESSION_HEALTH": {
        "report_id":           "COMPRESSION_HEALTH",
        "name":                "Compression Health",
        "report_family":       FAMILY_GOVERNANCE,
        "doctrine_version":    "1.26",
        "export_tier":         TIER_GOVERNANCE,
        "endpoint":            "/api/compression/health",
        "bundle_key":          "compression_health",
        "dependencies":        [],
        "overlapping_reports": ["COMPRESSION_ORCHESTRATION"],
        "constitutional_scope": "COMPRESSION_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 0},
        "description": "Compression subsystem health — operational status and buffer pressure diagnostics",
    },

    "COMPRESSION_ANOMALIES": {
        "report_id":           "COMPRESSION_ANOMALIES",
        "name":                "Compression Anomalies",
        "report_family":       FAMILY_GOVERNANCE,
        "doctrine_version":    "1.26",
        "export_tier":         TIER_GOVERNANCE,
        "endpoint":            "/api/compression/anomalies",
        "bundle_key":          "compression_anomalies",
        "dependencies":        ["COMPRESSION_HEALTH"],
        "overlapping_reports": ["COMPRESSION_ORCHESTRATION"],
        "constitutional_scope": "COMPRESSION_OBSERVABILITY",
        "archive_priority":    PRIORITY_MEDIUM,
        "evidence_requirements": {"min_trades": 0},
        "description": "Compression anomaly detection — identifies pathological compression patterns and overloads",
    },

    "COMPRESSION_ECOLOGY": {
        "report_id":           "COMPRESSION_ECOLOGY",
        "name":                "Compression Ecology",
        "report_family":       FAMILY_GOVERNANCE,
        "doctrine_version":    "1.26",
        "export_tier":         TIER_GOVERNANCE,
        "endpoint":            "/api/compression/ecology",
        "bundle_key":          "compression_ecology",
        "dependencies":        ["COMPRESSION_HEALTH"],
        "overlapping_reports": ["ECOLOGY", "COMPRESSION_ORCHESTRATION"],
        "constitutional_scope": "COMPRESSION_OBSERVABILITY",
        "archive_priority":    PRIORITY_MEDIUM,
        "evidence_requirements": {"min_trades": 10},
        "description": "Compression ecology — regime-indexed compression distribution and ecological balance",
    },

    "COMPRESSION_GOVERNANCE": {
        "report_id":           "COMPRESSION_GOVERNANCE",
        "name":                "Compression Governance",
        "report_family":       FAMILY_GOVERNANCE,
        "doctrine_version":    "1.26",
        "export_tier":         TIER_GOVERNANCE,
        "endpoint":            "/api/compression/governance",
        "bundle_key":          "compression_governance",
        "dependencies":        ["COMPRESSION_HEALTH", "COMPRESSION_ANOMALIES"],
        "overlapping_reports": ["COMPRESSION_ORCHESTRATION"],
        "constitutional_scope": "COMPRESSION_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 0},
        "description": "Compression governance compliance — constitutional alignment of compression operations",
    },

    "COMPRESSION_VISIBILITY": {
        "report_id":           "COMPRESSION_VISIBILITY",
        "name":                "Compression Visibility",
        "report_family":       FAMILY_GOVERNANCE,
        "doctrine_version":    "1.26",
        "export_tier":         TIER_GOVERNANCE,
        "endpoint":            "/api/compression/visibility",
        "bundle_key":          "compression_visibility",
        "dependencies":        ["COMPRESSION_HEALTH"],
        "overlapping_reports": ["COMPRESSION_ORCHESTRATION"],
        "constitutional_scope": "COMPRESSION_OBSERVABILITY",
        "archive_priority":    PRIORITY_MEDIUM,
        "evidence_requirements": {"min_trades": 0},
        "description": "Compression visibility diagnostics — operator-facing compression state transparency",
    },

    "COMPRESSION_ORCHESTRATION": {
        "report_id":           "COMPRESSION_ORCHESTRATION",
        "name":                "Compression Orchestration",
        "report_family":       FAMILY_GOVERNANCE,
        "doctrine_version":    "1.26",
        "export_tier":         TIER_GOVERNANCE,
        "endpoint":            "/api/compression/orchestration",
        "bundle_key":          "compression_orchestration",
        "dependencies":        [
            "COMPRESSION_EXECUTIVE", "COMPRESSION_HEALTH", "COMPRESSION_ANOMALIES",
            "COMPRESSION_ECOLOGY", "COMPRESSION_GOVERNANCE", "COMPRESSION_VISIBILITY",
        ],
        "overlapping_reports": ["COMPRESSION_EXECUTIVE"],
        "constitutional_scope": "COMPRESSION_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 0},
        "description": "Compression orchestration synthesis — unified compression intelligence across all sub-engines",
    },

    # ── Phase-D: Economic Truth Reconstruction ────────────────────────────────

    "EXPECTANCY_RECONSTRUCTION": {
        "report_id":           "EXPECTANCY_RECONSTRUCTION",
        "name":                "Expectancy Reconstruction",
        "report_family":       FAMILY_ECONOMIC,
        "doctrine_version":    "1.30",
        "export_tier":         TIER_RESEARCH,
        "endpoint":            "/api/economic-truth/expectancy",
        "bundle_key":          "expectancy_reconstruction",
        "dependencies":        ["ECONOMIC_GROUND_TRUTH"],
        "overlapping_reports": ["ECONOMIC_GROUND_TRUTH", "ECONOMIC_TRUTH"],
        "constitutional_scope": "ECONOMIC_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 10},
        "description": "Expectancy reconstruction — fee-adjusted, regime-segmented expectancy with survivability tiers",
    },

    "FEE_DRAG_INTELLIGENCE": {
        "report_id":           "FEE_DRAG_INTELLIGENCE",
        "name":                "Fee Drag Intelligence",
        "report_family":       FAMILY_ECONOMIC,
        "doctrine_version":    "1.30",
        "export_tier":         TIER_RESEARCH,
        "endpoint":            "/api/economic-truth/fee-drag",
        "bundle_key":          "fee_drag_intelligence",
        "dependencies":        ["ECONOMIC_GROUND_TRUTH"],
        "overlapping_reports": ["ECONOMIC_GROUND_TRUTH", "ECONOMIC_TRUTH"],
        "constitutional_scope": "ECONOMIC_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 5},
        "description": "Fee drag intelligence — true cost of trading with slippage, commissions, and drag decomposition",
    },

    "SURVIVABLE_ALPHA": {
        "report_id":           "SURVIVABLE_ALPHA",
        "name":                "Survivable Alpha Detection",
        "report_family":       FAMILY_ECONOMIC,
        "doctrine_version":    "1.30",
        "export_tier":         TIER_RESEARCH,
        "endpoint":            "/api/economic-truth/alpha",
        "bundle_key":          "survivable_alpha",
        "dependencies":        ["EXPECTANCY_RECONSTRUCTION", "FEE_DRAG_INTELLIGENCE"],
        "overlapping_reports": ["ALPHA_DISCOVERY", "ECONOMIC_TRUTH"],
        "constitutional_scope": "ECONOMIC_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 10},
        "description": "Survivable alpha detection — identifies edge that survives fees, regime shifts, and drawdown",
    },

    "ECONOMIC_ECOLOGICAL_COLLAPSE": {
        "report_id":           "ECONOMIC_ECOLOGICAL_COLLAPSE",
        "name":                "Ecological Collapse Detection",
        "report_family":       FAMILY_ECONOMIC,
        "doctrine_version":    "1.30",
        "export_tier":         TIER_RESEARCH,
        "endpoint":            "/api/economic-truth/ecology",
        "bundle_key":          "economic_ecological_collapse",
        "dependencies":        ["SURVIVABLE_ALPHA", "ECOLOGY"],
        "overlapping_reports": ["ECOLOGY", "ECONOMIC_TRUTH"],
        "constitutional_scope": "ECONOMIC_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 10},
        "description": "Ecological collapse detection — strategy ecosystem degradation and collapse risk signals",
    },

    "REGIME_SURVIVABILITY": {
        "report_id":           "REGIME_SURVIVABILITY",
        "name":                "Regime Survivability Engine",
        "report_family":       FAMILY_ECONOMIC,
        "doctrine_version":    "1.30",
        "export_tier":         TIER_RESEARCH,
        "endpoint":            "/api/economic-truth/regime",
        "bundle_key":          "regime_survivability",
        "dependencies":        ["ECONOMIC_GROUND_TRUTH", "REGIME_CARTOGRAPHY"],
        "overlapping_reports": ["REGIME_CARTOGRAPHY", "ECONOMIC_TRUTH"],
        "constitutional_scope": "ECONOMIC_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 20},
        "description": "Regime survivability engine — strategy viability across market regimes with transition mapping",
    },

    "ADAPTIVE_FILTRATION": {
        "report_id":           "ADAPTIVE_FILTRATION",
        "name":                "Adaptive Signal Filtration",
        "report_family":       FAMILY_ECONOMIC,
        "doctrine_version":    "1.30",
        "export_tier":         TIER_RESEARCH,
        "endpoint":            "/api/economic-truth/filtration",
        "bundle_key":          "adaptive_filtration",
        "dependencies":        ["EXPECTANCY_RECONSTRUCTION", "FEE_DRAG_INTELLIGENCE"],
        "overlapping_reports": ["ECONOMIC_TRUTH"],
        "constitutional_scope": "ECONOMIC_OBSERVABILITY",
        "archive_priority":    PRIORITY_MEDIUM,
        "evidence_requirements": {"min_trades": 10},
        "description": "Adaptive signal filtration — regime-aware signal quality scoring and noise suppression",
    },

    "ECONOMIC_TRUTH": {
        "report_id":           "ECONOMIC_TRUTH",
        "name":                "Economic Truth Orchestration",
        "report_family":       FAMILY_ECONOMIC,
        "doctrine_version":    "1.30",
        "export_tier":         TIER_CORE,
        "endpoint":            "/api/economic-truth/orchestration",
        "bundle_key":          "economic_truth",
        "dependencies":        [
            "EXPECTANCY_RECONSTRUCTION", "FEE_DRAG_INTELLIGENCE", "SURVIVABLE_ALPHA",
            "ECONOMIC_ECOLOGICAL_COLLAPSE", "REGIME_SURVIVABILITY", "ADAPTIVE_FILTRATION",
        ],
        "overlapping_reports": ["ECONOMIC_GROUND_TRUTH"],
        "constitutional_scope": "ECONOMIC_OBSERVABILITY",
        "archive_priority":    PRIORITY_CRITICAL,
        "evidence_requirements": {"min_trades": 10},
        "description": "Economic truth orchestration — Phase-D unified verdict with ECO lineage and constitutional invariants",
    },

    # ── Phase-E: Survivability Evolution ─────────────────────────────────────

    "EXPECTANCY_STABILITY": {
        "report_id":           "EXPECTANCY_STABILITY",
        "name":                "Expectancy Stability Engine",
        "report_family":       FAMILY_ECONOMIC,
        "doctrine_version":    "1.31",
        "export_tier":         TIER_RESEARCH,
        "endpoint":            "/api/survivability/expectancy-stability",
        "bundle_key":          "expectancy_stability",
        "dependencies":        ["EXPECTANCY_RECONSTRUCTION"],
        "overlapping_reports": ["EXPECTANCY_RECONSTRUCTION", "SURVIVABILITY_EVOLUTION"],
        "constitutional_scope": "ECONOMIC_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 10},
        "description": "Expectancy stability engine — rolling variance, trend, and regime-conditional stability scoring",
    },

    "ECOLOGICAL_PRESERVATION": {
        "report_id":           "ECOLOGICAL_PRESERVATION",
        "name":                "Ecological Self-Preservation Engine",
        "report_family":       FAMILY_ECONOMIC,
        "doctrine_version":    "1.31",
        "export_tier":         TIER_RESEARCH,
        "endpoint":            "/api/survivability/ecology-preservation",
        "bundle_key":          "ecological_preservation",
        "dependencies":        ["ECONOMIC_ECOLOGICAL_COLLAPSE"],
        "overlapping_reports": ["ECONOMIC_ECOLOGICAL_COLLAPSE", "SURVIVABILITY_EVOLUTION"],
        "constitutional_scope": "ECONOMIC_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 10},
        "description": "Ecological self-preservation — detects strategy extinction risk and self-correcting mechanisms",
    },

    "REGIME_MEMORY": {
        "report_id":           "REGIME_MEMORY",
        "name":                "Regime Adaptation Memory",
        "report_family":       FAMILY_ECONOMIC,
        "doctrine_version":    "1.31",
        "export_tier":         TIER_RESEARCH,
        "endpoint":            "/api/survivability/regime-memory",
        "bundle_key":          "regime_memory",
        "dependencies":        ["REGIME_SURVIVABILITY"],
        "overlapping_reports": ["REGIME_SURVIVABILITY", "SURVIVABILITY_EVOLUTION"],
        "constitutional_scope": "ECONOMIC_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 20},
        "description": "Regime adaptation memory — historical regime performance retained for cross-cycle comparison",
    },

    "ALPHA_PERSISTENCE": {
        "report_id":           "ALPHA_PERSISTENCE",
        "name":                "Alpha Persistence Tracker",
        "report_family":       FAMILY_ECONOMIC,
        "doctrine_version":    "1.31",
        "export_tier":         TIER_RESEARCH,
        "endpoint":            "/api/survivability/alpha-persistence",
        "bundle_key":          "alpha_persistence",
        "dependencies":        ["SURVIVABLE_ALPHA"],
        "overlapping_reports": ["SURVIVABLE_ALPHA", "SURVIVABILITY_EVOLUTION"],
        "constitutional_scope": "ECONOMIC_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 10},
        "description": "Alpha persistence tracker — measures alpha decay rate and long-term edge persistence",
    },

    "CONFIDENCE_REALISM": {
        "report_id":           "CONFIDENCE_REALISM",
        "name":                "Confidence Realism Engine",
        "report_family":       FAMILY_ECONOMIC,
        "doctrine_version":    "1.31",
        "export_tier":         TIER_RESEARCH,
        "endpoint":            "/api/survivability/confidence-realism",
        "bundle_key":          "confidence_realism",
        "dependencies":        ["EXPECTANCY_STABILITY"],
        "overlapping_reports": ["EXPECTANCY_STABILITY", "SURVIVABILITY_EVOLUTION"],
        "constitutional_scope": "ECONOMIC_OBSERVABILITY",
        "archive_priority":    PRIORITY_MEDIUM,
        "evidence_requirements": {"min_trades": 10},
        "description": "Confidence realism engine — calibration of strategy confidence against realized outcomes",
    },

    "ENTROPY_RESISTANCE": {
        "report_id":           "ENTROPY_RESISTANCE",
        "name":                "Entropy Resistance Engine",
        "report_family":       FAMILY_ECONOMIC,
        "doctrine_version":    "1.31",
        "export_tier":         TIER_RESEARCH,
        "endpoint":            "/api/survivability/entropy",
        "bundle_key":          "entropy_resistance",
        "dependencies":        ["EXPECTANCY_STABILITY", "ECOLOGICAL_PRESERVATION"],
        "overlapping_reports": ["SURVIVABILITY_EVOLUTION"],
        "constitutional_scope": "ECONOMIC_OBSERVABILITY",
        "archive_priority":    PRIORITY_MEDIUM,
        "evidence_requirements": {"min_trades": 10},
        "description": "Entropy resistance engine — measures strategy information degradation and disorder accumulation",
    },

    "SURVIVABILITY_EVOLUTION": {
        "report_id":           "SURVIVABILITY_EVOLUTION",
        "name":                "Survivability Evolution Orchestration",
        "report_family":       FAMILY_ECONOMIC,
        "doctrine_version":    "1.31",
        "export_tier":         TIER_CORE,
        "endpoint":            "/api/survivability/orchestration",
        "bundle_key":          "survivability_evolution",
        "dependencies":        [
            "EXPECTANCY_STABILITY", "ECOLOGICAL_PRESERVATION", "REGIME_MEMORY",
            "ALPHA_PERSISTENCE", "CONFIDENCE_REALISM", "ENTROPY_RESISTANCE",
        ],
        "overlapping_reports": ["ECONOMIC_TRUTH"],
        "constitutional_scope": "ECONOMIC_OBSERVABILITY",
        "archive_priority":    PRIORITY_CRITICAL,
        "evidence_requirements": {"min_trades": 10},
        "description": "Survivability evolution orchestration — Phase-E unified verdict with SURV lineage, EVOLVING→COLLAPSING tiers",
    },

    # ── Phase-G: Adaptive Execution Governance ────────────────────────────────

    "RESTRAINT_ADVISORY": {
        "report_id":           "RESTRAINT_ADVISORY",
        "name":                "Restraint Advisory Engine",
        "report_family":       FAMILY_GOVERNANCE,
        "doctrine_version":    "1.33",
        "export_tier":         TIER_GOVERNANCE,
        "endpoint":            "/api/execution-governance/restraint",
        "bundle_key":          "restraint_advisory",
        "dependencies":        ["ECONOMIC_TRUTH", "SURVIVABILITY_EVOLUTION"],
        "overlapping_reports": ["EXECUTION_CIVILIZATION"],
        "constitutional_scope": "GOVERNANCE_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 0},
        "description": "Restraint advisory engine — G.1 execution advisory with TRADE_ALLOWED→ENTROPY_ALERT states",
    },

    "DISCIPLINE_GATE": {
        "report_id":           "DISCIPLINE_GATE",
        "name":                "Capital Discipline Gate",
        "report_family":       FAMILY_GOVERNANCE,
        "doctrine_version":    "1.33",
        "export_tier":         TIER_GOVERNANCE,
        "endpoint":            "/api/execution-governance/discipline-gate",
        "bundle_key":          "discipline_gate",
        "dependencies":        ["RESTRAINT_ADVISORY"],
        "overlapping_reports": ["EXECUTION_CIVILIZATION"],
        "constitutional_scope": "GOVERNANCE_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 0},
        "description": "Capital discipline gate — G.2 constitutional execution gate with PASS/CAUTION/DEFENSIVE/UNSAFE states",
    },

    "EQUILIBRIUM_RESUMPTION": {
        "report_id":           "EQUILIBRIUM_RESUMPTION",
        "name":                "Equilibrium Resumption Engine",
        "report_family":       FAMILY_GOVERNANCE,
        "doctrine_version":    "1.33",
        "export_tier":         TIER_GOVERNANCE,
        "endpoint":            "/api/execution-governance/equilibrium",
        "bundle_key":          "equilibrium_resumption",
        "dependencies":        ["DISCIPLINE_GATE"],
        "overlapping_reports": ["EXECUTION_CIVILIZATION"],
        "constitutional_scope": "GOVERNANCE_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 0},
        "description": "Equilibrium resumption engine — G.3 recovery readiness with ACTIVE→LOCKDOWN states and 6 dimensions",
    },

    "OVERRIDE_TRANSPARENCY": {
        "report_id":           "OVERRIDE_TRANSPARENCY",
        "name":                "Operator Override Transparency",
        "report_family":       FAMILY_HUMAN_ALIGNMENT,
        "doctrine_version":    "1.33",
        "export_tier":         TIER_GOVERNANCE,
        "endpoint":            "/api/execution-governance/overrides",
        "bundle_key":          "override_transparency",
        "dependencies":        ["RESTRAINT_ADVISORY"],
        "overlapping_reports": ["EXECUTION_CIVILIZATION"],
        "constitutional_scope": "ALIGNMENT_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 0},
        "description": "Operator override transparency — G.4 detects explicit and inferred overrides with human-visible audit trail",
    },

    "DISCIPLINE_MEMORY": {
        "report_id":           "DISCIPLINE_MEMORY",
        "name":                "Execution Discipline Memory",
        "report_family":       FAMILY_GOVERNANCE,
        "doctrine_version":    "1.33",
        "export_tier":         TIER_GOVERNANCE,
        "endpoint":            "/api/execution-governance/discipline-memory",
        "bundle_key":          "discipline_memory",
        "dependencies":        ["DISCIPLINE_GATE"],
        "overlapping_reports": ["EXECUTION_CIVILIZATION"],
        "constitutional_scope": "GOVERNANCE_OBSERVABILITY",
        "archive_priority":    PRIORITY_MEDIUM,
        "evidence_requirements": {"min_trades": 10},
        "description": "Execution discipline memory — G.5 behavioral memory with DISCIPLINED→UNCONTROLLED tiers",
    },

    "GOVERNANCE_SAFETY": {
        "report_id":           "GOVERNANCE_SAFETY",
        "name":                "Human Governance Safety Engine",
        "report_family":       FAMILY_HUMAN_ALIGNMENT,
        "doctrine_version":    "1.33",
        "export_tier":         TIER_GOVERNANCE,
        "endpoint":            "/api/execution-governance/governance-safety",
        "bundle_key":          "governance_safety",
        "dependencies":        [
            "RESTRAINT_ADVISORY", "DISCIPLINE_GATE", "EQUILIBRIUM_RESUMPTION",
            "OVERRIDE_TRANSPARENCY", "DISCIPLINE_MEMORY",
        ],
        "overlapping_reports": ["EXECUTION_CIVILIZATION"],
        "constitutional_scope": "ALIGNMENT_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 0},
        "description": "Human governance safety — G.6 validates G.1–G.5 integrity with CERTIFIED/VIOLATION_DETECTED states",
    },

    "EXECUTION_CIVILIZATION": {
        "report_id":           "EXECUTION_CIVILIZATION",
        "name":                "Adaptive Execution Civilization",
        "report_family":       FAMILY_GOVERNANCE,
        "doctrine_version":    "1.33",
        "export_tier":         TIER_GOVERNANCE,
        "endpoint":            "/api/execution-governance/orchestration",
        "bundle_key":          "execution_civilization",
        "dependencies":        [
            "RESTRAINT_ADVISORY", "DISCIPLINE_GATE", "EQUILIBRIUM_RESUMPTION",
            "OVERRIDE_TRANSPARENCY", "DISCIPLINE_MEMORY", "GOVERNANCE_SAFETY",
        ],
        "overlapping_reports": ["SURVIVABILITY_EVOLUTION"],
        "constitutional_scope": "GOVERNANCE_OBSERVABILITY",
        "archive_priority":    PRIORITY_CRITICAL,
        "evidence_requirements": {"min_trades": 0},
        "description": "Adaptive execution civilization — Phase-G SOVEREIGN/OPERATIONAL/GUARDED/COMPROMISED tiers with EXEC lineage",
    },

    # ── Phase-H: Institutional Continuity ────────────────────────────────────

    "MULTI_CYCLE_SURVIVABILITY": {
        "report_id":           "MULTI_CYCLE_SURVIVABILITY",
        "name":                "Multi-Cycle Survivability Memory",
        "report_family":       FAMILY_CONTINUITY,
        "doctrine_version":    "1.34",
        "export_tier":         TIER_CONTINUITY,
        "endpoint":            "/api/continuity/survivability-memory",
        "bundle_key":          "multi_cycle_survivability",
        "dependencies":        ["SURVIVABILITY_EVOLUTION"],
        "overlapping_reports": ["INSTITUTIONAL_CONTINUITY"],
        "constitutional_scope": "CONTINUITY_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 10},
        "description": "Multi-cycle survivability memory — H.1 era detection with DURABLE/CYCLICAL/DETERIORATING verdicts",
    },

    "EVOLUTIONARY_DOCTRINE": {
        "report_id":           "EVOLUTIONARY_DOCTRINE",
        "name":                "Evolutionary Doctrine Memory",
        "report_family":       FAMILY_CONTINUITY,
        "doctrine_version":    "1.34",
        "export_tier":         TIER_CONTINUITY,
        "endpoint":            "/api/continuity/doctrine",
        "bundle_key":          "evolutionary_doctrine",
        "dependencies":        ["MULTI_CYCLE_SURVIVABILITY"],
        "overlapping_reports": ["INSTITUTIONAL_CONTINUITY"],
        "constitutional_scope": "CONTINUITY_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 20},
        "description": "Evolutionary doctrine memory — H.2 quartile drift analysis with STABLE/DRIFTING/REGRESSED/EVOLVING states",
    },

    "LONG_HORIZON_ENTROPY": {
        "report_id":           "LONG_HORIZON_ENTROPY",
        "name":                "Long-Horizon Entropy Engine",
        "report_family":       FAMILY_CONTINUITY,
        "doctrine_version":    "1.34",
        "export_tier":         TIER_CONTINUITY,
        "endpoint":            "/api/continuity/entropy",
        "bundle_key":          "long_horizon_entropy",
        "dependencies":        ["SURVIVABILITY_EVOLUTION"],
        "overlapping_reports": ["ENTROPY_RESISTANCE", "INSTITUTIONAL_CONTINUITY"],
        "constitutional_scope": "CONTINUITY_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 10},
        "description": "Long-horizon entropy engine — H.3 slow-degradation detection with DURABLE/AGING/FRAGILE/EXHAUSTED states",
    },

    "RECOVERY_INHERITANCE": {
        "report_id":           "RECOVERY_INHERITANCE",
        "name":                "Institutional Recovery Inheritance",
        "report_family":       FAMILY_CONTINUITY,
        "doctrine_version":    "1.34",
        "export_tier":         TIER_CONTINUITY,
        "endpoint":            "/api/continuity/recovery",
        "bundle_key":          "recovery_inheritance",
        "dependencies":        ["MULTI_CYCLE_SURVIVABILITY"],
        "overlapping_reports": ["INSTITUTIONAL_CONTINUITY"],
        "constitutional_scope": "CONTINUITY_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 10},
        "description": "Recovery inheritance — H.4 crossover-based inheritance with RICH/MODERATE/SPARSE/NO_INHERITANCE states",
    },

    "CROSS_REGIME_CONTINUITY": {
        "report_id":           "CROSS_REGIME_CONTINUITY",
        "name":                "Cross-Regime Continuity Engine",
        "report_family":       FAMILY_CONTINUITY,
        "doctrine_version":    "1.34",
        "export_tier":         TIER_CONTINUITY,
        "endpoint":            "/api/continuity/cross-regime",
        "bundle_key":          "cross_regime_continuity",
        "dependencies":        ["REGIME_SURVIVABILITY", "REGIME_MEMORY"],
        "overlapping_reports": ["REGIME_MEMORY", "INSTITUTIONAL_CONTINUITY"],
        "constitutional_scope": "CONTINUITY_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 20},
        "description": "Cross-regime continuity — H.5 UNIVERSAL/BROAD/NARROW/FRAGILE verdicts across 6 environment types",
    },

    "INSTITUTIONAL_IDENTITY": {
        "report_id":           "INSTITUTIONAL_IDENTITY",
        "name":                "Institutional Identity Stability",
        "report_family":       FAMILY_CONTINUITY,
        "doctrine_version":    "1.34",
        "export_tier":         TIER_CONTINUITY,
        "endpoint":            "/api/continuity/identity",
        "bundle_key":          "institutional_identity",
        "dependencies":        ["EXECUTION_CIVILIZATION"],
        "overlapping_reports": ["EXECUTION_CIVILIZATION", "INSTITUTIONAL_CONTINUITY"],
        "constitutional_scope": "CONTINUITY_OBSERVABILITY",
        "archive_priority":    PRIORITY_HIGH,
        "evidence_requirements": {"min_trades": 0},
        "description": "Institutional identity stability — H.6 detects HIDDEN_SOVEREIGNTY_DRIFT and GOVERNANCE_EROSION with STABLE→COMPROMISED states",
    },

    "INSTITUTIONAL_CONTINUITY": {
        "report_id":           "INSTITUTIONAL_CONTINUITY",
        "name":                "Institutional Continuity Orchestration",
        "report_family":       FAMILY_CONTINUITY,
        "doctrine_version":    "1.34",
        "export_tier":         TIER_CONTINUITY,
        "endpoint":            "/api/continuity/orchestration",
        "bundle_key":          "institutional_continuity",
        "dependencies":        [
            "MULTI_CYCLE_SURVIVABILITY", "EVOLUTIONARY_DOCTRINE", "LONG_HORIZON_ENTROPY",
            "RECOVERY_INHERITANCE", "CROSS_REGIME_CONTINUITY", "INSTITUTIONAL_IDENTITY",
        ],
        "overlapping_reports": ["EXECUTION_CIVILIZATION"],
        "constitutional_scope": "CONTINUITY_OBSERVABILITY",
        "archive_priority":    PRIORITY_CRITICAL,
        "evidence_requirements": {"min_trades": 10},
        "description": "Institutional continuity orchestration — Phase-H ENDURING/PERSISTENT/FRAGILE/DECAYING tiers with CONT lineage",
    },
}

# Total registered reports — must equal len(REPORT_REGISTRY)
EXPECTED_REPORT_COUNT = 75
