"""
FTD-SESSION-FORENSICS — Origin vs Receiver Session Attribution Analyzer

Reads all trades from the DataLake and answers the core research question:

    Do losses disproportionately cross session boundaries, meaning that
    receiving sessions absorb delayed losses generated by earlier-session
    entry conditions?

Output sections:
  1. Attribution coverage — % of trades with origin_session populated
  2. Origin-session win/loss/WR breakdown
  3. Close-session win/loss/WR breakdown (current RL attribution target)
  4. Cross-boundary concentration — winner vs loser boundary-cross rates
  5. Boundary transition matrix (origin→close counts, win/loss split)
  6. Hold-duration asymmetry — the key evidence for the hypothesis
  7. Session role classification — originator / receiver / absorber

Usage:
    python tools/analyze_session_boundary_crossings.py
    python tools/analyze_session_boundary_crossings.py --db path/to/data_lake.db
    python tools/analyze_session_boundary_crossings.py --json
    python tools/analyze_session_boundary_crossings.py --verbose
"""
from __future__ import annotations

import argparse
import json
import sqlite3
import sys
from collections import Counter, defaultdict
from pathlib import Path
from statistics import mean, median, stdev

_HERE = Path(__file__).resolve().parent
_PROJECT_ROOT = _HERE.parent
DEFAULT_DB = _PROJECT_ROOT / "data" / "data_lake.db"

SESSION_ORDER = ["ASIA", "LONDON", "NY", "LATE"]


# ── DataLake loader ───────────────────────────────────────────────────────────

def _load_trades(db_path: Path) -> list[dict]:
    if not db_path.exists():
        print(f"[ERROR] Database not found: {db_path}", file=sys.stderr)
        sys.exit(1)
    conn = sqlite3.connect(db_path)
    try:
        cur = conn.execute("SELECT data FROM trades ORDER BY ts ASC")
        rows = cur.fetchall()
    except sqlite3.OperationalError as exc:
        print(f"[ERROR] {exc}", file=sys.stderr)
        sys.exit(1)
    finally:
        conn.close()
    trades = []
    for (blob,) in rows:
        try:
            trades.append(json.loads(blob))
        except json.JSONDecodeError:
            pass
    return trades


# ── Analysis ──────────────────────────────────────────────────────────────────

def _stats(values: list[float]) -> dict:
    if not values:
        return {"n": 0, "mean": None, "median": None, "min": None, "max": None, "stdev": None}
    return {
        "n":      len(values),
        "mean":   round(mean(values), 1),
        "median": round(median(values), 1),
        "min":    round(min(values), 1),
        "max":    round(max(values), 1),
        "stdev":  round(stdev(values), 1) if len(values) > 1 else None,
    }


def _wr(wins: int, losses: int) -> float | None:
    n = wins + losses
    return round(wins / n * 100, 1) if n else None


def analyse(trades: list[dict]) -> dict:
    total = len(trades)
    attributed = [t for t in trades
                  if t.get("origin_session", "UNKNOWN") not in ("UNKNOWN", "", None)]
    n_attr = len(attributed)

    # ── Per-session accumulators ──────────────────────────────────────────────
    orig_wins:  dict[str, int] = defaultdict(int)
    orig_loss:  dict[str, int] = defaultdict(int)
    close_wins: dict[str, int] = defaultdict(int)
    close_loss: dict[str, int] = defaultdict(int)

    # hold times in seconds
    hold_by_orig_win:  dict[str, list] = defaultdict(list)
    hold_by_orig_loss: dict[str, list] = defaultdict(list)
    hold_by_close_win: dict[str, list] = defaultdict(list)
    hold_by_close_loss: dict[str, list] = defaultdict(list)

    all_winners_hold: list = []
    all_losers_hold:  list = []

    # ── Cross-boundary accumulators ───────────────────────────────────────────
    # transition_detail: {transition_str: {"wins": int, "losses": int, "hold_sec": [...]}}
    transition_detail: dict[str, dict] = defaultdict(lambda: {"wins": 0, "losses": 0, "hold_sec": []})

    cross_winner_hold: list = []
    cross_loser_hold:  list = []
    same_winner_hold:  list = []
    same_loser_hold:   list = []

    for tr in attributed:
        origin  = tr.get("origin_session", "UNKNOWN")
        close   = tr.get("close_session",  "UNKNOWN")
        pnl     = tr.get("net_pnl", 0.0)
        won     = pnl >= 0
        hold_ms = max(0, tr.get("exit_ts", 0) - tr.get("entry_ts", 0))
        hold_s  = hold_ms / 1000.0
        crossed = tr.get("crossed_session_boundary", origin != close)

        (orig_wins if won else orig_loss)[origin] += 1
        if close not in ("UNKNOWN", "", None):
            (close_wins if won else close_loss)[close] += 1

        if won:
            hold_by_orig_win[origin].append(hold_s)
            if close not in ("UNKNOWN", "", None):
                hold_by_close_win[close].append(hold_s)
            all_winners_hold.append(hold_s)
        else:
            hold_by_orig_loss[origin].append(hold_s)
            if close not in ("UNKNOWN", "", None):
                hold_by_close_loss[close].append(hold_s)
            all_losers_hold.append(hold_s)

        if crossed:
            transition = tr.get("boundary_transition") or f"{origin}→{close}"
            transition_detail[transition]["hold_sec"].append(hold_s)
            if won:
                transition_detail[transition]["wins"] += 1
                cross_winner_hold.append(hold_s)
            else:
                transition_detail[transition]["losses"] += 1
                cross_loser_hold.append(hold_s)
        else:
            if won:
                same_winner_hold.append(hold_s)
            else:
                same_loser_hold.append(hold_s)

    # ── Build session-level summaries ─────────────────────────────────────────
    all_sessions = (
        sorted(set(orig_wins) | set(orig_loss), key=lambda s: SESSION_ORDER.index(s)
               if s in SESSION_ORDER else 99)
    )

    origin_summary = {}
    for s in all_sessions:
        w, l = orig_wins[s], orig_loss[s]
        origin_summary[s] = {
            "wins": w, "losses": l,
            "win_rate_pct": _wr(w, l),
            "hold_winners_sec": _stats(hold_by_orig_win[s]),
            "hold_losers_sec":  _stats(hold_by_orig_loss[s]),
        }

    close_sessions = sorted(
        set(close_wins) | set(close_loss),
        key=lambda s: SESSION_ORDER.index(s) if s in SESSION_ORDER else 99,
    )
    close_summary = {}
    for s in close_sessions:
        w, l = close_wins[s], close_loss[s]
        close_summary[s] = {
            "wins": w, "losses": l,
            "win_rate_pct": _wr(w, l),
            "hold_winners_sec": _stats(hold_by_close_win[s]),
            "hold_losers_sec":  _stats(hold_by_close_loss[s]),
        }

    # ── Boundary transition matrix ────────────────────────────────────────────
    transition_matrix = {}
    for trans, data in sorted(transition_detail.items(),
                               key=lambda x: -(x[1]["wins"] + x[1]["losses"])):
        w, l = data["wins"], data["losses"]
        transition_matrix[trans] = {
            "wins": w, "losses": l,
            "win_rate_pct": _wr(w, l),
            "avg_hold_sec": round(mean(data["hold_sec"]), 1) if data["hold_sec"] else None,
        }

    total_cross = len(cross_winner_hold) + len(cross_loser_hold)
    total_same  = len(same_winner_hold) + len(same_loser_hold)
    n_winners   = len(all_winners_hold)
    n_losers    = len(all_losers_hold)

    # ── Session role classifier ───────────────────────────────────────────────
    # Originator: high origin_wins — signal quality spawns there
    # Absorber:   high close_losses received from other sessions
    # Balanced:   roughly equal origin and close attribution
    def _role(sess: str) -> str:
        ow = orig_wins.get(sess, 0) + orig_loss.get(sess, 0)
        cl = close_wins.get(sess, 0) + close_loss.get(sess, 0)
        cl_losses_from_cross = sum(
            d["losses"] for t, d in transition_detail.items()
            if t.endswith(f"→{sess}")
        )
        if cl == 0:
            return "ORIGINATOR_ONLY"
        absorbed_ratio = cl_losses_from_cross / cl if cl > 0 else 0
        if absorbed_ratio > 0.4:
            return "ABSORBER"
        if ow > cl * 1.3:
            return "ORIGINATOR"
        if cl > ow * 1.3:
            return "RECEIVER"
        return "BALANCED"

    session_roles = {s: _role(s) for s in all_sessions}

    return {
        "coverage": {
            "total_trades":       total,
            "attributed_trades":  n_attr,
            "coverage_pct":       round(n_attr / total * 100, 1) if total else 0.0,
            "legacy_note":        (
                "Trades with origin_session='UNKNOWN' pre-date FTD-SESSION-FORENSICS "
                "deployment.  Only attributed trades are analysed below."
            ),
        },
        "origin_session_breakdown":  origin_summary,
        "close_session_breakdown":   close_summary,
        "cross_boundary": {
            "total":              total_cross,
            "same_session":       total_same,
            "winner_cross_count": len(cross_winner_hold),
            "loser_cross_count":  len(cross_loser_hold),
            "winner_cross_pct":   round(len(cross_winner_hold) / n_winners * 100, 1) if n_winners else None,
            "loser_cross_pct":    round(len(cross_loser_hold)  / n_losers  * 100, 1) if n_losers  else None,
            "hold_cross_winners_sec": _stats(cross_winner_hold),
            "hold_cross_losers_sec":  _stats(cross_loser_hold),
            "hold_same_winners_sec":  _stats(same_winner_hold),
            "hold_same_losers_sec":   _stats(same_loser_hold),
        },
        "boundary_transition_matrix": transition_matrix,
        "hold_duration_summary": {
            "all_winners_sec": _stats(all_winners_hold),
            "all_losers_sec":  _stats(all_losers_hold),
            "hold_asymmetry_sec": (
                round(mean(all_losers_hold) - mean(all_winners_hold), 1)
                if all_winners_hold and all_losers_hold else None
            ),
            "hypothesis_note": (
                "Positive hold_asymmetry_sec (losers hold longer than winners) "
                "is consistent with the origin-receiver distortion hypothesis.  "
                "The magnitude indicates how many seconds of delay separates "
                "loser attribution from winner attribution."
            ),
        },
        "session_role_classification": session_roles,
    }


# ── Report printing ───────────────────────────────────────────────────────────

def _print_report(result: dict, verbose: bool = False) -> None:
    w = 66
    cov = result["coverage"]
    print(f"\n{'='*w}")
    print("  FTD-SESSION-FORENSICS — Origin vs Receiver Attribution Report")
    print(f"{'='*w}")
    print(f"  Total trades   : {cov['total_trades']}")
    print(f"  Attributed     : {cov['attributed_trades']}  ({cov['coverage_pct']:.1f}%)")
    if cov["attributed_trades"] == 0:
        print(f"\n  No attributed trades yet. "
              f"Run engine after FTD-SESSION-FORENSICS deployment.\n")
        return

    print(f"\n  Origin-Session Win Rates (signal origination geography)")
    print(f"  {'Session':<10} {'Wins':>6} {'Losses':>7} {'WR%':>6}  "
          f"{'Avg Win Hold':>14}  {'Avg Loss Hold':>14}")
    for sess, d in result["origin_session_breakdown"].items():
        wh = d["hold_winners_sec"]
        lh = d["hold_losers_sec"]
        wh_s = f"{wh['mean']:.0f}s" if wh["mean"] is not None else "—"
        lh_s = f"{lh['mean']:.0f}s" if lh["mean"] is not None else "—"
        wr = f"{d['win_rate_pct']:.1f}%" if d["win_rate_pct"] is not None else "—"
        print(f"  {sess:<10} {d['wins']:>6} {d['losses']:>7} {wr:>6}  "
              f"{wh_s:>14}  {lh_s:>14}")

    print(f"\n  Close-Session Win Rates (current RL attribution target)")
    print(f"  {'Session':<10} {'Wins':>6} {'Losses':>7} {'WR%':>6}")
    for sess, d in result["close_session_breakdown"].items():
        wr = f"{d['win_rate_pct']:.1f}%" if d["win_rate_pct"] is not None else "—"
        print(f"  {sess:<10} {d['wins']:>6} {d['losses']:>7} {wr:>6}")

    cb = result["cross_boundary"]
    print(f"\n  Cross-Boundary Analysis")
    print(f"  Total cross-boundary trades : {cb['total']}")
    print(f"  Same-session trades         : {cb['same_session']}")
    wcp = f"{cb['winner_cross_pct']:.1f}%" if cb["winner_cross_pct"] is not None else "—"
    lcp = f"{cb['loser_cross_pct']:.1f}%" if cb["loser_cross_pct"] is not None else "—"
    print(f"  Winners crossing boundary   : {cb['winner_cross_count']}  ({wcp} of all winners)")
    print(f"  Losers crossing boundary    : {cb['loser_cross_count']}  ({lcp} of all losers)")

    hd = result["hold_duration_summary"]
    print(f"\n  Hold-Duration Asymmetry (key evidence for attribution hypothesis)")
    wm = f"{hd['all_winners_sec']['mean']:.0f}s" if hd["all_winners_sec"]["mean"] is not None else "—"
    lm = f"{hd['all_losers_sec']['mean']:.0f}s" if hd["all_losers_sec"]["mean"] is not None else "—"
    asym = hd["hold_asymmetry_sec"]
    asym_s = f"{asym:+.0f}s" if asym is not None else "—"
    print(f"  Avg winner hold : {wm}")
    print(f"  Avg loser hold  : {lm}")
    print(f"  Asymmetry       : {asym_s}  (positive = losers hold longer)")
    if asym and asym > 0:
        print(f"  ⚠  DISTORTION SIGNAL: losers hold {asym:.0f}s longer than winners.")
        print(f"     Receiving sessions may absorb origin-session losses.")
    elif asym and asym < 0:
        print(f"  ✓  No distortion signal: winners hold longer than losers.")

    tm = result["boundary_transition_matrix"]
    if tm:
        print(f"\n  Boundary Transition Matrix")
        print(f"  {'Transition':<15} {'Total':>6} {'WR%':>6}  {'Avg Hold':>10}")
        for trans, d in list(tm.items())[:10]:
            wr = f"{d['win_rate_pct']:.1f}%" if d["win_rate_pct"] is not None else "—"
            ah = f"{d['avg_hold_sec']:.0f}s" if d["avg_hold_sec"] is not None else "—"
            n  = d["wins"] + d["losses"]
            print(f"  {trans:<15} {n:>6} {wr:>6}  {ah:>10}")

    roles = result["session_role_classification"]
    if roles:
        print(f"\n  Session Role Classification")
        for sess, role in roles.items():
            print(f"  {sess:<10} : {role}")

    print(f"\n{'='*w}\n")


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Analyze session boundary crossings for origin-receiver attribution")
    parser.add_argument("--db", default=str(DEFAULT_DB))
    parser.add_argument("--json",    action="store_true", dest="emit_json")
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    trades = _load_trades(Path(args.db))
    result = analyse(trades)

    if args.emit_json:
        print(json.dumps(result, indent=2))
    else:
        _print_report(result, verbose=args.verbose)


if __name__ == "__main__":
    main()
